name: Test and deploy
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  call-test-workflow:
    uses: ./.github/workflows/test.yaml
    secrets:
      TWITTER_API_KEY: '${{ secrets.TWITTER_API_KEY }}'
      TWITTER_API_SECRET: '${{ secrets.TWITTER_API_SECRET }}'
      TWITTER_ACCESS_TOKEN: '${{ secrets.TWITTER_ACCESS_TOKEN }}'
      TWITTER_ACCESS_SECRET: '${{ secrets.TWITTER_ACCESS_SECRET }}'
      TWITTER_BEARER_TOKEN: '${{ secrets.TWITTER_BEARER_TOKEN }}'
  docker:
    name: Publish - Docker Hub
    environment: production
    runs-on: ubuntu-20.04
    needs: [call-test-workflow]
    env:
      REPO: davidlopezsaez/yes-i-hate-it
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        run: docker login -u '${{ secrets.DOCKER_USER }}'
             -p '${{ secrets.DOCKER_PASS }}'
      - name: Build Docker image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image
        run: docker push $REPO
  redeploy:
    name: Redeploy webhook call
    environment: production
    runs-on: ubuntu-20.04
    needs: [docker]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: '${{ secrets.DEPLOY_WEBHOOK_URL }}'
          data: "{'redeploy': true}"
